name: Pipeline

on:
  push:
    branches: [ main ]

 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm --prefix frontend install
    - run: npm run --prefix frontend test -- --watchAll=false --coverage=true
    - run: npx --prefix frontend eslint .
    - run: npm --prefix frontend run build
    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: frontend/build
        
  acceptance:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: echo "Estágio acceptance"
    
  release:
    runs-on: ubuntu-latest
    needs: acceptance
    steps:
    - run: echo "Estágio release"

  getArtifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: echo "Pegar artefato"

  copyToBucket:
    runs-on: ubuntu-latest
    needs: getArtifact
    steps:
    - run: echo "Copia para S3"

